<template>
  <input
    type="text"
    class="
      rounded-full
      bg-transparent
      text-purple-400
      hover:text-white
      placeholder-purple-500
      border border-purple-700
      focus:border-purple-600
      focus:text-white
      hover:border-purple-600
      focus:shadow-2xl
      hover
      py-2
      px-6
      transition
      duration-300
      ease-in-out
      outline-none
    "
  />
</template>
