<template>
  <div
    class="
      z-10
      absolute
      bg-gray-800
      bottom-24
      left-0
      rounded-xl
      md:bottom-0 md:right-0 md:left-auto md:rounded-b-none md:rounded-tr-none
      rounded-tl-xl
      shadow-xl
      px-4
      py-3
    "
  >
    <slot/>
  </div>
</template>
